dependencies:
- name: zeebe-cluster-k8s-helm
  version: 0.0.24
  repository: http://jenkins-x-chartmuseum:8080
- name: zeebe-operate-k8s-helm
  version: 0.0.12
  repository: http://jenkins-x-chartmuseum:8080
- name: nginx-ingress
  version: 1.19.0
  repository: https://kubernetes-charts.storage.googleapis.com
  
