zeebe-k8s-full-helm: 
  kibana: 
    healthCheckPath: "/logs/app/kibana"
    extraEnvs:
      - name: SERVER_BASEPATH
        value: /logs
      - name: SERVER_REWRITEBASEPATH
        value: "true"
    ingress:
      enabled: true
      hosts:
        - "*/logs"
      annotations:
        kubernetes.io/ingress.class: nginx
zeebe-operate-k8s-helm:
  zeebe: "{{ .Release.Name }}-zeebe-k8s-full-helm"

