# Default values for zeebe-k8s-full-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
zeebe-operate-k8s-helm:
  zeebe: {{ .Release.Name }}"-zeebe-cluster-k8s-helm"
zeebe-cluster-k8s-helm: 
  kibana: 
    healthCheckPath: "/logs/app/kibana"
    extraEnvs:
      - name: SERVER_BASEPATH
        value: /logs
      - name: SERVER_REWRITEBASEPATH
        value: "true"
    ingress:
      enabled: true
      host: ""
      path: /logs
      annotations:
        kubernetes.io/ingress.class: nginx
