zeebe-cluster-k8s-helm: 
  kibana: 
    healthCheckPath: "/logs/app/kibana"
    extraEnvs:
      - name: SERVER_BASEPATH
        value: /logs
      - name: SERVER_REWRITEBASEPATH
        value: "true"
    ingress:
      enabled: true
      host: "*"
      path: /logs
      annotations:
        kubernetes.io/ingress.class: nginx
zeebe-operate-k8s-helm:
  zeebe: "{{- tpl .Release.Name . }}-zeebe-cluster-k8s-helm"

