zeebe-cluster-k8s-helm: 
  kibana: 
    healthCheckPath: "/logs/app/kibana"
    ingress:
      enabled: false
      annotations: {}
        kubernetes.io/ingress.class: nginx
      path: /logs
      hosts:
        - ""
    extraEnvs:
      - name: SERVER_BASEPATH
        value: /logs
      - name: SERVER_REWRITEBASEPATH
        value: "true"
      annotations:
        kubernetes.io/ingress.class: nginx
zeebe-operate-k8s-helm:
  zeebe: "{{ .Release.Name }}-zeebe-cluster-k8s-helm"

